name: simple-scan-pipeline
on:
  push:
    branches:
    - main
jobs:
  scan:
    name: simple-scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: 1
        ignore-unfixed: true
